"""initial schema

Revision ID: 38c3e7468447
Revises:
Create Date: 2026-08-29 09:22:57.046057

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38c3e7468447'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables créées dans l'ordre des dépendances de clés étrangères :
    # users -> google_connections -> websites -> website_google_links ->
    # audit_snapshots -> issue_items -> audit_log
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_users_google_sub'))
    )
    op.create_table('google_connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('google_account_email', sa.String(length=320), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('granted_scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEEDS_REAUTH', 'REVOKED', name='connection_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_google_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_connections')),
    sa.UniqueConstraint('user_id', 'google_sub', name='user_google_sub')
    )
    op.create_index(op.f('ix_google_connections_user_id'), 'google_connections', ['user_id'], unique=False)
    op.create_table('websites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_websites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites')),
    sa.UniqueConstraint('user_id', 'domain', name='user_domain')
    )
    op.create_index(op.f('ix_websites_user_id'), 'websites', ['user_id'], unique=False)
    op.create_table('website_google_links',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('google_connection_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('GA4_PROPERTY', 'GTM_CONTAINER', 'GSC_SITE', name='resource_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_display_name', sa.String(length=255), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['google_connection_id'], ['google_connections.id'], name=op.f('fk_website_google_links_google_connection_id_google_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_website_google_links_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_google_links')),
    sa.UniqueConstraint('website_id', 'resource_type', 'resource_id', name='website_resource')
    )
    op.create_index(op.f('ix_website_google_links_google_connection_id'), 'website_google_links', ['google_connection_id'], unique=False)
    op.create_index(op.f('ix_website_google_links_website_id'), 'website_google_links', ['website_id'], unique=False)
    op.create_table('audit_snapshots',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('PAGESPEED', 'GA4', 'GSC', 'COMPOSITE', name='snapshot_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_audit_snapshots_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_snapshots'))
    )
    op.create_index('ix_audit_snapshots_website_captured', 'audit_snapshots', ['website_id', 'captured_at'], unique=False)
    op.create_table('issue_items',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SEO', 'ANALYTICS', 'CWV', 'TRACKING', 'OTHER', name='issue_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issue_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'FIXED', 'DISMISSED', name='issue_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['audit_snapshots.id'], name=op.f('fk_issue_items_source_snapshot_id_audit_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_issue_items_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_items')),
    sa.UniqueConstraint('website_id', 'fingerprint', name='website_fingerprint')
    )
    op.create_index(op.f('ix_issue_items_website_id'), 'issue_items', ['website_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('google_connection_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('request_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'ERROR', name='audit_result', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['google_connection_id'], ['google_connections.id'], name=op.f('fk_audit_log_google_connection_id_google_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_user_created', 'audit_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ordre inverse de upgrade().
    op.drop_index('ix_audit_log_user_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_issue_items_website_id'), table_name='issue_items')
    op.drop_table('issue_items')
    op.drop_index('ix_audit_snapshots_website_captured', table_name='audit_snapshots')
    op.drop_table('audit_snapshots')
    op.drop_index(op.f('ix_website_google_links_website_id'), table_name='website_google_links')
    op.drop_index(op.f('ix_website_google_links_google_connection_id'), table_name='website_google_links')
    op.drop_table('website_google_links')
    op.drop_index(op.f('ix_websites_user_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_google_connections_user_id'), table_name='google_connections')
    op.drop_table('google_connections')
    op.drop_table('users')
    # ### end Alembic commands ###
