"""advisor tables

Revision ID: a653b32f47a4
Revises: 0c6d572e41fe
Create Date: 2026-09-10 22:48:08.451764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a653b32f47a4"
down_revision: str | Sequence[str] | None = "0c6d572e41fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisor_usage",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("brief_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("message_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_advisor_usage_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "day", name=op.f("pk_advisor_usage")),
    )
    op.create_table(
        "user_advisor_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("persona_key", sa.String(length=32), server_default="consultant", nullable=False),
        sa.Column("custom_prompt", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_advisor_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_advisor_settings")),
    )
    op.create_table(
        "advisor_threads",
        sa.Column("website_id", sa.Uuid(), nullable=False),
        sa.Column("persona_key", sa.String(length=32), nullable=False),
        sa.Column("custom_prompt_snapshot", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["audit_snapshots.id"],
            name=op.f("fk_advisor_threads_source_snapshot_id_audit_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_advisor_threads_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisor_threads")),
    )
    op.create_index(
        op.f("ix_advisor_threads_website_id"), "advisor_threads", ["website_id"], unique=False
    )
    op.create_table(
        "advisor_messages",
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["advisor_threads.id"],
            name=op.f("fk_advisor_messages_thread_id_advisor_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisor_messages")),
    )
    op.create_index(
        op.f("ix_advisor_messages_thread_id"), "advisor_messages", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_advisor_messages_thread_id"), table_name="advisor_messages")
    op.drop_table("advisor_messages")
    op.drop_index(op.f("ix_advisor_threads_website_id"), table_name="advisor_threads")
    op.drop_table("advisor_threads")
    op.drop_table("user_advisor_settings")
    op.drop_table("advisor_usage")
    # ### end Alembic commands ###
