"""website_detected_stack

Revision ID: d24c2a97270e
Revises: e266e9a27496
Create Date: 2026-08-30 03:17:51.808110

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d24c2a97270e"
down_revision: str | Sequence[str] | None = "e266e9a27496"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websites",
        sa.Column(
            "detected_stack",
            sa.Enum(
                "nextjs",
                "wordpress",
                "woocommerce",
                "nuxt",
                "vue",
                "angular",
                "generic",
                "unknown",
                name="stack_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websites", "detected_stack")
    # ### end Alembic commands ###
