"""advisor actions

Revision ID: f1572fec5930
Revises: a653b32f47a4
Create Date: 2026-09-11 12:57:53.008596

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1572fec5930"
down_revision: str | Sequence[str] | None = "a653b32f47a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisor_tool_calls",
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("tool", sa.String(length=32), nullable=False),
        sa.Column(
            "called_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["advisor_threads.id"],
            name=op.f("fk_advisor_tool_calls_thread_id_advisor_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisor_tool_calls")),
    )
    op.create_index(
        op.f("ix_advisor_tool_calls_thread_id"), "advisor_tool_calls", ["thread_id"], unique=False
    )
    op.add_column(
        "advisor_threads", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advisor_threads", "archived_at")
    op.drop_index(op.f("ix_advisor_tool_calls_thread_id"), table_name="advisor_tool_calls")
    op.drop_table("advisor_tool_calls")
    # ### end Alembic commands ###
